// config.bin - 17:18:02 06/27/22, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

class CfgPatches {
	class NeonM_Lights_Models {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgMods {
	class NeonM_Lights_Models {
		dir = "NeonM_Lights_Models";
		picture = "";
		action = "";
		hideName = 1;
		hidePicture = 1;
		name = "NeonM_Lights_Models";
		credits = "NeonMurder";
		author = "NeonMurder";
		authorID = 76561198102181067;
		version = 0.1;
		extra = 0;
		type = "mod";
	};
};

class CfgVehicles {
	class HouseNoDestruct;	// External class reference
	class Fireplace;	// External class reference
	class PortableGasLamp;	// External class reference
	
	class NM_KeroseneLamp : PortableGasLamp {
		scope = public;
		model = "NeonM_Lights_Models\Models\KeroseneLamp.p3d";
		attachments[] = {};
		
		class GUIInventoryAttachmentsProps {};
	};
	
	class NM_KeroseneLamp_2 : PortableGasLamp {
		scope = public;
		model = "NeonM_Lights_Models\Models\KeroseneLamp_2.p3d";
		attachments[] = {};
		
		class GUIInventoryAttachmentsProps {};
	};
	
	class NM_CampFire_Empty : Fireplace {
		scope = public;
		model = "NeonM_Lights_Models\Models\CampfireEmpty.p3d";
		itemsCargoSize[] = {10, 50};
		attachments[] = {};
		
		class GUIInventoryAttachmentsProps {};
	};
	
	class NM_CampFire : Fireplace {
		scope = public;
		model = "NeonM_Lights_Models\Models\Campfire.p3d";
		itemsCargoSize[] = {10, 50};
		attachments[] = {};
		
		class GUIInventoryAttachmentsProps {};
	};
	
	class NM_Torch : HouseNoDestruct {
		scope = public;
		model = "NeonM_Lights_Models\Models\Torch.p3d";
	};
	
	class NM_StreetLamp : HouseNoDestruct {
		scope = public;
		model = "NeonM_Lights_Models\Models\StreetLamp.p3d";
		oldpower = 0;
		inputRange = 8;
		useEntityHierarchy = "true";
		
		class EnergyManager {
			hasIcon = 1;
			autoSwitchOff = 1;
			energyUsagePerSecond = 0.15;
			attachmentAction = 1;
		};
	};
	
	class NM_Lamp : HouseNoDestruct {
		scope = public;
		model = "NeonM_Lights_Models\Models\Lamp.p3d";
		oldpower = 0;
		inputRange = 8;
		useEntityHierarchy = "true";
		
		class EnergyManager {
			hasIcon = 1;
			autoSwitchOff = 1;
			energyUsagePerSecond = 0.15;
			attachmentAction = 1;
		};
	};
	
	class NM_IndustrialLamp : HouseNoDestruct {
		scope = public;
		model = "NeonM_Lights_Models\Models\IndustrialLamp.p3d";
		oldpower = 0;
		inputRange = 8;
		useEntityHierarchy = "true";
		
		class EnergyManager {
			hasIcon = 1;
			autoSwitchOff = 1;
			energyUsagePerSecond = 0.15;
			attachmentAction = 1;
		};
	};
	
	class NM_LightTower : HouseNoDestruct {
		scope = public;
		model = "NeonM_Lights_Models\Models\LightTower.p3d";
		oldpower = 0;
		inputRange = 8;
		useEntityHierarchy = "true";
		
		class EnergyManager {
			hasIcon = 1;
			autoSwitchOff = 1;
			energyUsagePerSecond = 0.15;
			attachmentAction = 1;
		};
	};
};
